version: '3.8'

services:
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=medisupply-project
    ports:
      - "8085:8085"
    environment:
      - PUBSUB_PROJECT_ID=medisupply-project
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085"]
      interval: 30s
      timeout: 10s
      retries: 3

  productos:
    build: ./Productos
    ports:
      - "5000:5000"
    depends_on:
      - pubsub-emulator
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - PUBSUB_PROJECT_ID=medisupply-project
      - FLASK_APP=src.api
      - PYTHONPATH=/app
      - FLASK_ENV=development
    volumes:
      - ./Productos/src:/app/src