apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  namespace: medisupply
type: Opaque
data:
  # Base64 encoded service account key
  # Reemplazar con: echo -n '{"type": "service_account", ...}' | base64
  service-account-key.json: ""
